# Generated by Django 5.0.6 on 2024-05-29 00:49

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                (
                    "email",
                    models.EmailField(
                        max_length=255,
                        unique=True,
                        validators=[
                            django.core.validators.EmailValidator(
                                message="Enter a valid email address."
                            )
                        ],
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        max_length=15,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid phone number. It may contain digits, spaces, and optionally start with a '+'.",
                                regex="^\\+?[0-9\\- ]+$",
                            )
                        ],
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("street", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("zip_code", models.CharField(max_length=20)),
                ("country", models.CharField(max_length=100)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shipping_addresses",
                        to="umico_app.customer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Frame",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deadline", models.DateTimeField()),
                ("image_height", models.DecimalField(decimal_places=2, max_digits=8)),
                ("image_width", models.DecimalField(decimal_places=2, max_digits=8)),
                ("frame_height", models.DecimalField(decimal_places=2, max_digits=8)),
                ("frame_width", models.DecimalField(decimal_places=2, max_digits=8)),
                ("moulding", models.CharField(max_length=50)),
                ("moulding_number", models.BigIntegerField(default=23423)),
                ("mat", models.CharField(max_length=50)),
                ("mat_number", models.BigIntegerField(default=23432)),
                ("mat_ply", models.CharField(max_length=50)),
                ("mat_window", models.BooleanField()),
                ("mat_double", models.BooleanField()),
                ("mat_in_visible", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "mat_in_total",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
                ),
                (
                    "mat_inside_height",
                    models.DecimalField(decimal_places=2, max_digits=8),
                ),
                (
                    "mat_inside_width",
                    models.DecimalField(decimal_places=2, max_digits=8),
                ),
                (
                    "mat_outside_height",
                    models.DecimalField(decimal_places=2, max_digits=8),
                ),
                (
                    "mat_outside_width",
                    models.DecimalField(decimal_places=2, max_digits=8),
                ),
                ("float_type", models.CharField(max_length=50)),
                (
                    "float_in_visible",
                    models.DecimalField(decimal_places=2, max_digits=8),
                ),
                ("float_in_total", models.DecimalField(decimal_places=2, max_digits=8)),
                ("glazing", models.CharField(max_length=50)),
                (
                    "thumbnail",
                    models.CharField(
                        default="/static/images/placeholder.svg", max_length=250
                    ),
                ),
                ("glazing_type", models.CharField(max_length=50)),
                ("spacers", models.BooleanField()),
                ("spacers_type", models.CharField(max_length=50)),
                ("canvas_floater", models.DecimalField(decimal_places=2, max_digits=8)),
                ("straight_to_frame", models.BooleanField()),
                ("art_location", models.CharField(max_length=50)),
                ("art_condition", models.TextField()),
                ("is_completed", models.BooleanField()),
                ("client_notified", models.BooleanField()),
                ("notification_date", models.DateTimeField(blank=True, null=True)),
                ("final_location", models.CharField(max_length=50)),
                ("payment_type", models.CharField(max_length=50)),
                ("deposit", models.BooleanField()),
                ("balance_paid", models.BooleanField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="umico_app.customer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Print",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deadline", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("image_height", models.DecimalField(decimal_places=2, max_digits=8)),
                ("image_width", models.DecimalField(decimal_places=2, max_digits=8)),
                ("paper_height", models.DecimalField(decimal_places=2, max_digits=8)),
                ("paper_width", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "thumbnail",
                    models.CharField(
                        default="/static/images/placeholder.svg", max_length=250
                    ),
                ),
                ("print_style", models.CharField(max_length=50)),
                ("quantity", models.IntegerField()),
                ("job_notes", models.TextField()),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="umico_app.customer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Scan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deadline", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("image_height", models.DecimalField(decimal_places=2, max_digits=8)),
                ("image_width", models.DecimalField(decimal_places=2, max_digits=8)),
                ("file_type", models.CharField(max_length=50)),
                ("dpi", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "thumbnail",
                    models.CharField(
                        default="/static/images/placeholder.svg", max_length=250
                    ),
                ),
                ("is_completed", models.BooleanField()),
                ("client_notified", models.BooleanField()),
                ("notification_date", models.DateTimeField(blank=True, null=True)),
                ("final_location", models.CharField(max_length=50)),
                ("payment_type", models.CharField(max_length=50)),
                ("deposit_made", models.BooleanField()),
                ("balance_paid", models.BooleanField()),
                ("job_notes", models.TextField(default="No notes at this time")),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="umico_app.customer",
                    ),
                ),
            ],
        ),
    ]
