# Generated by Django 5.0.6 on 2024-06-05 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("umico_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="frame",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="frames",
                to="umico_app.customer",
            ),
        ),
        migrations.AlterField(
            model_name="print",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prints",
                to="umico_app.customer",
            ),
        ),
        migrations.AlterField(
            model_name="scan",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scans",
                to="umico_app.customer",
            ),
        ),
    ]
