# Generated by Django 5.0.6 on 2024-05-16 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("umico_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="frame",
            name="canvas_floater",
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name="frame",
            name="float_in_total",
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name="frame",
            name="float_in_visible",
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name="frame",
            name="frame_height",
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name="frame",
            name="frame_width",
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name="frame",
            name="image_height",
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name="frame",
            name="image_width",
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name="frame",
            name="mat_in_visible",
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name="frame",
            name="mat_inside_height",
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name="frame",
            name="mat_inside_width",
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name="frame",
            name="mat_outside_height",
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name="frame",
            name="mat_outside_width",
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name="frame",
            name="moulding",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="print",
            name="image_height",
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name="print",
            name="image_width",
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name="print",
            name="paper_height",
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name="print",
            name="paper_width",
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name="scan",
            name="dpi",
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name="scan",
            name="image_height",
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name="scan",
            name="image_width",
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
