# Generated by Django 5.0.6 on 2024-06-18 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("umico_app", "0002_alter_frame_customer_alter_print_customer_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="print",
            name="thumbnail",
        ),
        migrations.RemoveField(
            model_name="scan",
            name="deposit_made",
        ),
        migrations.RemoveField(
            model_name="scan",
            name="job_notes",
        ),
        migrations.RemoveField(
            model_name="scan",
            name="thumbnail",
        ),
        migrations.AddField(
            model_name="frame",
            name="float",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="frame",
            name="job_notes",
            field=models.TextField(default="No notes at this time"),
        ),
        migrations.AddField(
            model_name="print",
            name="balance_paid",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="print",
            name="client_notified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="print",
            name="deposit",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="print",
            name="final_location",
            field=models.CharField(default="N/A", max_length=50),
        ),
        migrations.AddField(
            model_name="print",
            name="is_completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="print",
            name="notification_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="print",
            name="payment_type",
            field=models.CharField(default="Visa", max_length=50),
        ),
        migrations.AddField(
            model_name="scan",
            name="deposit",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="frame",
            name="art_condition",
            field=models.TextField(default="N/A"),
        ),
        migrations.AlterField(
            model_name="frame",
            name="balance_paid",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="frame",
            name="canvas_floater",
            field=models.DecimalField(decimal_places=3, max_digits=8),
        ),
        migrations.AlterField(
            model_name="frame",
            name="client_notified",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="frame",
            name="deposit",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="frame",
            name="float_in_total",
            field=models.DecimalField(decimal_places=3, max_digits=8),
        ),
        migrations.AlterField(
            model_name="frame",
            name="float_in_visible",
            field=models.DecimalField(decimal_places=3, max_digits=8),
        ),
        migrations.AlterField(
            model_name="frame",
            name="frame_height",
            field=models.DecimalField(decimal_places=3, max_digits=8),
        ),
        migrations.AlterField(
            model_name="frame",
            name="frame_width",
            field=models.DecimalField(decimal_places=3, max_digits=8),
        ),
        migrations.AlterField(
            model_name="frame",
            name="image_height",
            field=models.DecimalField(decimal_places=3, max_digits=8),
        ),
        migrations.AlterField(
            model_name="frame",
            name="image_width",
            field=models.DecimalField(decimal_places=3, max_digits=8),
        ),
        migrations.AlterField(
            model_name="frame",
            name="is_completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="frame",
            name="mat_in_total",
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name="frame",
            name="mat_in_visible",
            field=models.DecimalField(decimal_places=3, max_digits=8),
        ),
        migrations.AlterField(
            model_name="frame",
            name="mat_inside_height",
            field=models.DecimalField(decimal_places=3, max_digits=8),
        ),
        migrations.AlterField(
            model_name="frame",
            name="mat_inside_width",
            field=models.DecimalField(decimal_places=3, max_digits=8),
        ),
        migrations.AlterField(
            model_name="frame",
            name="mat_outside_height",
            field=models.DecimalField(decimal_places=3, max_digits=8),
        ),
        migrations.AlterField(
            model_name="frame",
            name="mat_outside_width",
            field=models.DecimalField(decimal_places=3, max_digits=8),
        ),
        migrations.AlterField(
            model_name="frame",
            name="payment_type",
            field=models.CharField(default="Visa", max_length=50),
        ),
        migrations.AlterField(
            model_name="frame",
            name="spacers",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="frame",
            name="straight_to_frame",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="print",
            name="image_height",
            field=models.DecimalField(decimal_places=3, max_digits=8),
        ),
        migrations.AlterField(
            model_name="print",
            name="image_width",
            field=models.DecimalField(decimal_places=3, max_digits=8),
        ),
        migrations.AlterField(
            model_name="print",
            name="job_notes",
            field=models.TextField(default="N/A"),
        ),
        migrations.AlterField(
            model_name="print",
            name="paper_height",
            field=models.DecimalField(decimal_places=3, max_digits=8),
        ),
        migrations.AlterField(
            model_name="print",
            name="paper_width",
            field=models.DecimalField(decimal_places=3, max_digits=8),
        ),
        migrations.AlterField(
            model_name="print",
            name="quantity",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="scan",
            name="balance_paid",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="scan",
            name="client_notified",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="scan",
            name="dpi",
            field=models.DecimalField(decimal_places=3, max_digits=8),
        ),
        migrations.AlterField(
            model_name="scan",
            name="final_location",
            field=models.CharField(default="N/A", max_length=50),
        ),
        migrations.AlterField(
            model_name="scan",
            name="image_height",
            field=models.DecimalField(decimal_places=3, max_digits=8),
        ),
        migrations.AlterField(
            model_name="scan",
            name="image_width",
            field=models.DecimalField(decimal_places=3, max_digits=8),
        ),
        migrations.AlterField(
            model_name="scan",
            name="is_completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="scan",
            name="payment_type",
            field=models.CharField(default="Visa", max_length=50),
        ),
    ]
