# Generated by Django 5.0.6 on 2024-05-18 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("umico_app", "0003_alter_frame_notification_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="print",
            name="thumbnail",
            field=models.CharField(
                default="/static/images/placeholder.svg", max_length=250
            ),
        ),
        migrations.AlterField(
            model_name="frame",
            name="thumbnail",
            field=models.CharField(
                default="/static/images/placeholder.svg", max_length=250
            ),
        ),
        migrations.AlterField(
            model_name="scan",
            name="thumbnail",
            field=models.CharField(
                default="/static/images/placeholder.svg", max_length=250
            ),
        ),
    ]
