# Generated by Django 5.0.6 on 2024-06-18 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("umico_app", "0003_remove_print_thumbnail_remove_scan_deposit_made_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Misc",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deadline", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("job_notes", models.TextField(default="No notes at this time")),
                ("is_completed", models.BooleanField(default=False)),
                ("client_notified", models.BooleanField(default=False)),
                ("notification_date", models.DateTimeField(blank=True, null=True)),
                ("final_location", models.CharField(max_length=50)),
                ("payment_type", models.CharField(default="Visa", max_length=50)),
                ("deposit", models.BooleanField(default=False)),
                ("balance_paid", models.BooleanField(default=False)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="misc",
                        to="umico_app.customer",
                    ),
                ),
            ],
        ),
    ]
