# Generated by Django 5.0.6 on 2024-05-24 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("umico_app", "0004_print_thumbnail_alter_frame_thumbnail_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="frame",
            name="mat_in_total",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name="frame",
            name="mat_number",
            field=models.BigIntegerField(default=23432),
        ),
        migrations.AddField(
            model_name="frame",
            name="moulding_number",
            field=models.BigIntegerField(default=23423),
        ),
    ]
